env: local
http:
  host: 127.0.0.1
  port: 8080
security:
  api_sign:
    app_key: 123456
    app_security: 123456
  jwt:
    key: QQYnRFerJTSEcrfB89fw8prOaObmrch8
data:
  db:
    user:
      driver: mysql
      dsn: root:ranen1024@tcp(119.3.152.220:33060)/data_center_cn?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 119.3.152.220:63790
    password: "ranen1024"
    db: 0
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  log_level: debug
  encoding: console           # json or console
  log_file_name: "./storage/logs/server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true
